const fonts = {
  Raleway: {
    Black: 'Raleway-Black',
    BlackItalic: 'Raleway-BlackItalic',
    Bold: 'Raleway-Bold',
    BoldItalic: 'Raleway-BoldItalic',
    ExtraBold: 'Raleway-ExtraBold',
    ExtraBoldItalic: 'Raleway-ExtraBoldItalic',
    ExtraLight: 'Raleway-ExtraLight',
    ExtraLightItalic: 'Raleway-ExtraLightItalic',
    Italic: 'Raleway-Italic',
    Light: 'Raleway-Light',
    LightItalic: 'Raleway-LightItalic',
    Medium: 'Raleway-Medium',
    MediumItalic: 'Raleway-MediumItalic',
    Regular: 'Raleway-Regular',
    SemiBold: 'Raleway-SemiBold',
    SemiBoldItalic: 'Raleway-SemiBoldItalic',
    Thin: 'Raleway-Thin',
    ThinItalic: 'Raleway-ThinItalic',
  },
  Poppins: {
    Black: 'Poppins-Black',
    BlackItalic: 'Poppins-BlackItalic',
    Bold: 'Poppins-Bold',
    BoldItalic: 'Poppins-BoldItalic',
    ExtraBold: 'Poppins-ExtraBold',
    ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    ExtraLight: 'Poppins-ExtraLight',
    ExtraLightItalic: 'Poppins-ExtraLightItalic',
    Italic: 'Poppins-Italic',
    Light: 'Poppins-Light',
    LightItalic: 'Poppins-LightItalic',
    Medium: 'Poppins-Medium',
    MediumItalic: 'Poppins-MediumItalic',
    Regular: 'Poppins-Regular',
    SemiBold: 'Poppins-SemiBold',
    SemiBoldItalic: 'Poppins-SemiBoldItalic',
    Thin: 'Poppins-Thin',
    ThinItalic: 'Poppins-ThinItalic',
  },
  NunitoSans: {
    Black: 'NunitoSans-Black',
    BlackItalic: 'NunitoSans-BlackItalic',
    Bold: 'NunitoSans-Bold',
    BoldItalic: 'NunitoSans-BoldItalic',
    ExtraBold: 'NunitoSans-ExtraBold',
    ExtraBoldItalic: 'NunitoSans-ExtraBoldItalic',
    ExtraLight: 'NunitoSans-ExtraLight',
    ExtraLightItalic: 'NunitoSans-ExtraLightItalic',
    Italic: 'NunitoSans-Italic',
    Light: 'NunitoSans-Light',
    LightItalic: 'NunitoSans-LightItalic',
    Medium: 'NunitoSans-Medium',
    MediumItalic: 'NunitoSans-MediumItalic',
    Regular: 'NunitoSans-Regular',
    SemiBold: 'NunitoSans-SemiBold',
    SemiBoldItalic: 'NunitoSans-SemiBoldItalic',
  },
};

export default fonts;
