export const images = {
  bagIcon: require('../assets/images/bagIcon/bagIcon.png'),
  appBackgroundImage: require('../assets/images/splash/splash.png'),
  circleBack: require('../assets/images/cicleBack/cicleBack.png'),
  signupBubble: require('../assets/images/signupBubbles/Bubble.png'),
  cameraIcon: require('../assets/icons/cameraIcon/cameraIcon.png'),
  eye: require('../assets/icons/eye/Eye.png'),
  eyeClosed: require('../assets/icons/eyeClose/eyeClose.png'),
  arrowDown: require('../assets/icons/arrowDown/arrowDown.png'),
  search: require('../assets/icons/search/search.png'),
  loginBg: require('../assets/images/loginBg/login.png'),
  heart: require('../assets/images/heart/heart.png'),
  passwrdBg: require('../assets/images/passwrdBg/passwrdBg.png'),
  searchCross: require('../assets/icons/searchCross/Cross.png'),
  profileImage: require('../assets/images/profileImage/profileImage.png'),
  forgotPassBg: require('../assets/images/forgotPassBg/forgotPassBg.png'),
  whiteTick: require('../assets/icons/whiteTick/whiteTick.png'),
  Exclamation: require('../assets/icons/Exclamation/Exclamation.png'),
  homeIcon: require('../assets/icons/homeIcon/Home.png'),
  favourite: require('../assets/icons/favourite/favorite.png'),
  cartIcon: require('../assets/icons/Cart/Cart.png'),
  profileIcon: require('../assets/icons/Profile/profile.png'),
  category: require('../assets/icons/category/Categories.png'),
  dashboardBg: require('../assets/images/dashboardBg/dashboardBg.png'),
  whiteClock: require('../assets/images/whiteClock/clock.png'),
};
