export const texts = {
  Shoppe: 'Shoppe',
  landing_subtitle: 'Beautiful eCommerce UI Kit for your online store',
  started_button: "Let's get started",
  not_have_accnt: `Don't have an account`,
  ok: 'Ok',
  search: 'Search',
  done: 'Done',
  noAvaiable: 'Not Available',
  cancel: 'Cancel',
  password: 'Password',
  fullName: 'Full Name',
  yourNumber: 'Your Number',
  email: 'Email',
  login: 'Log In',
  forgotPassword: 'Forgot Password',
};
